<?php


/**
 * This class defines the structure of the 'follower' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Sat Mar 20 22:52:34 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FollowerTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FollowerTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('follower');
		$this->setPhpName('Follower');
		$this->setClassname('Follower');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('FOLLOWING', 'Following', 'BOOLEAN', true, null, null);
		$this->addColumn('SENDER_ID', 'SenderId', 'BIGINT', true, null, null);
		$this->addColumn('SENDER_NAME', 'SenderName', 'VARCHAR', false, 20, null);
		$this->addColumn('SENDER_SCREEN_NAME', 'SenderScreenName', 'VARCHAR', true, 15, null);
		$this->addColumn('SENDER_DESCRIPTION', 'SenderDescription', 'VARCHAR', false, 160, null);
		$this->addColumn('SENDER_LOCATION', 'SenderLocation', 'VARCHAR', false, 255, null);
		$this->addColumn('SENDER_PROTECTED', 'SenderProtected', 'BOOLEAN', true, null, null);
		$this->addColumn('SENDER_PROFILE_IMG', 'SenderProfileImg', 'VARCHAR', true, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('RawDm', 'RawDm', RelationMap::ONE_TO_MANY, array('id' => 'follower_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // FollowerTableMap
