<?php


/**
 * Skeleton subclass for performing query and update operations on the 'follower' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Sat Mar 20 22:11:35 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FollowerPeer extends BaseFollowerPeer
{

    public static function createFollower(array $rawfollower, PropelPDO $con = null)
    {
        $crit = new Criteria();
        $crit->add(self::SENDER_ID, $rawfollower['id']);

        $follower = self::doSelectOne($crit, $con);

        if (is_null($follower))
        {
            $t = new Twitter(sfConfig::get('twitter_username'), sfConfig::get('twitter_password'));
            $t->createFriendship($rawfollower['id']);

            $follower = new Follower();
            $follower->setFollowing(true);
            $follower->setSenderId($rawfollower['id']);
            $follower->setSenderName($rawfollower['name']);
            $follower->setSenderScreenName($rawfollower['screen_name']);
            $follower->setSenderLocation($rawfollower['location']);
            $follower->setSenderProfileImg($rawfollower['profile_image_url']);
            $follower->setSenderProtected($rawfollower['protected']);
            $follower->save();
        }

        return $follower;
    }
} // FollowerPeer
