<?php


/**
 * Skeleton subclass for representing a row from the 'raw_dm' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Sat Mar 20 21:30:17 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RawDm extends BaseRawDm {

} // RawDm
