<?php


/**
 * Skeleton subclass for representing a row from the 'raw_message' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon Mar 29 23:12:03 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RawMessage extends BaseRawMessage {

} // RawMessage
